const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT 
global.appUrl=process.env.APP_URL || ""     // put your deploy app/bot url here, for 24/7 for (render , koyeb, glitch)
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || "false" || "mongodb+srv://mohsin:mohsin@cluster0.iauaztt.mongodb.net/?retryWrites=true&w=majority"
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || "false" || "mongodb+srv://mohsin:mohsin@cluster0.iauaztt.mongodb.net/?retryWrites=true&w=majority"

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/suhailmd-2.0";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029VagJIAr3bbVBCpEkAM07";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029VagJIAr3bbVBCpEkAM07" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://i.ibb.co/TgwRyHR/Ephoto360-com-166de101e03cd7.jpg" || "https://i.ibb.co/bH1kbX0/a4c0b1af253197d4837ff6760d5b81c0.jpg" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "© SuhailTechInfo" 


global.devs = "923314926746" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "923038652067";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923038652067";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '5'  // put '5' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || Math.floor(Math.random()*3)  === 1 ?  "false" : "false" ;  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "https://i.ibb.co/pXyNHj8/suhail.jpg" // "image" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com/" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID  || "SUHAIL_10_32_07_09_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNzIsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMTI4LFxuICAgICAgICAyNDEsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMyxcbiAgICAgICAgMTIwLFxuICAgICAgICAyNDUsXG4gICAgICAgIDE1NSxcbiAgICAgICAgOTcsXG4gICAgICAgIDE1NixcbiAgICAgICAgMjUzLFxuICAgICAgICAyMTAsXG4gICAgICAgIDgsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMzgsXG4gICAgICAgIDEyLFxuICAgICAgICAyMjAsXG4gICAgICAgIDU5LFxuICAgICAgICA0OSxcbiAgICAgICAgMixcbiAgICAgICAgMTEwLFxuICAgICAgICAyOCxcbiAgICAgICAgNjUsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMTc4LFxuICAgICAgICAyMjEsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTY1LFxuICAgICAgICA4MixcbiAgICAgICAgNzAsXG4gICAgICAgIDcxXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQsXG4gICAgICAgIDEyLFxuICAgICAgICAxMDcsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMTE1LFxuICAgICAgICA5MixcbiAgICAgICAgMTE0LFxuICAgICAgICAxMTMsXG4gICAgICAgIDQxLFxuICAgICAgICA2NCxcbiAgICAgICAgMjE2LFxuICAgICAgICA5LFxuICAgICAgICAxNjQsXG4gICAgICAgIDUwLFxuICAgICAgICA2NixcbiAgICAgICAgMTQ2LFxuICAgICAgICAxMTYsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMjA1LFxuICAgICAgICAxNTUsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMjUyLFxuICAgICAgICA0MixcbiAgICAgICAgMjAsXG4gICAgICAgIDk0LFxuICAgICAgICA0LFxuICAgICAgICAyNDYsXG4gICAgICAgIDE0MSxcbiAgICAgICAgNzksXG4gICAgICAgIDIwLFxuICAgICAgICAxMixcbiAgICAgICAgNzlcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE0NCxcbiAgICAgICAgMjM5LFxuICAgICAgICAyMDMsXG4gICAgICAgIDEwNixcbiAgICAgICAgNDIsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTU2LFxuICAgICAgICAzNCxcbiAgICAgICAgODksXG4gICAgICAgIDIyMixcbiAgICAgICAgMTM4LFxuICAgICAgICAyMjksXG4gICAgICAgIDEwMSxcbiAgICAgICAgMjE3LFxuICAgICAgICAyMjAsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMTEyLFxuICAgICAgICAxNTgsXG4gICAgICAgIDc2LFxuICAgICAgICA0MyxcbiAgICAgICAgMjQwLFxuICAgICAgICAxMCxcbiAgICAgICAgNjYsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMjgsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMjksXG4gICAgICAgIDE3NyxcbiAgICAgICAgMzAsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTY2LFxuICAgICAgICAxMTFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTc3LFxuICAgICAgICAyNTMsXG4gICAgICAgIDE4NCxcbiAgICAgICAgNjIsXG4gICAgICAgIDIyNixcbiAgICAgICAgMjM3LFxuICAgICAgICA3MixcbiAgICAgICAgMjQ5LFxuICAgICAgICA5MixcbiAgICAgICAgNTIsXG4gICAgICAgIDUxLFxuICAgICAgICAxMzUsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTgzLFxuICAgICAgICA1MCxcbiAgICAgICAgNjcsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMTc5LFxuICAgICAgICAxMjksXG4gICAgICAgIDY0LFxuICAgICAgICA4NCxcbiAgICAgICAgMTA4LFxuICAgICAgICA2LFxuICAgICAgICAyNDEsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTUxLFxuICAgICAgICAyMzAsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMTY2LFxuICAgICAgICAxMjgsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMzFcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEyMCxcbiAgICAgICAgNjIsXG4gICAgICAgIDIzOCxcbiAgICAgICAgNzUsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMTE5LFxuICAgICAgICAxMzgsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTU2LFxuICAgICAgICA5OCxcbiAgICAgICAgMjM5LFxuICAgICAgICAzNSxcbiAgICAgICAgMTI4LFxuICAgICAgICAyMDAsXG4gICAgICAgIDIyLFxuICAgICAgICAxOTcsXG4gICAgICAgIDE3LFxuICAgICAgICAwLFxuICAgICAgICAxOTIsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMzksXG4gICAgICAgIDkwLFxuICAgICAgICAxMDcsXG4gICAgICAgIDY2LFxuICAgICAgICAyNTIsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTg3LFxuICAgICAgICAxNzAsXG4gICAgICAgIDc3LFxuICAgICAgICAyNTMsXG4gICAgICAgIDEzNixcbiAgICAgICAgNjVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNTEsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMTM4LFxuICAgICAgICAxNjMsXG4gICAgICAgIDk5LFxuICAgICAgICA1MyxcbiAgICAgICAgMTQ1LFxuICAgICAgICAxMDgsXG4gICAgICAgIDEzNixcbiAgICAgICAgMTE1LFxuICAgICAgICA2LFxuICAgICAgICAzNCxcbiAgICAgICAgMTQyLFxuICAgICAgICAyMSxcbiAgICAgICAgNzIsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMjMyLFxuICAgICAgICAxMDYsXG4gICAgICAgIDIzMixcbiAgICAgICAgMTc3LFxuICAgICAgICAxNjcsXG4gICAgICAgIDcsXG4gICAgICAgIDY3LFxuICAgICAgICAxNTAsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMTk4LFxuICAgICAgICAxMjcsXG4gICAgICAgIDE5LFxuICAgICAgICAyMTUsXG4gICAgICAgIDE2LFxuICAgICAgICAxNjAsXG4gICAgICAgIDY5XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDExMixcbiAgICAgICAgICAyNTEsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgNzUsXG4gICAgICAgICAgODUsXG4gICAgICAgICAgMTkxLFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICA3NCxcbiAgICAgICAgICAyMDIsXG4gICAgICAgICAgMTE2LFxuICAgICAgICAgIDIxMixcbiAgICAgICAgICA4MSxcbiAgICAgICAgICA0OSxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgMCxcbiAgICAgICAgICAxMyxcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgOTQsXG4gICAgICAgICAgMyxcbiAgICAgICAgICAxMzMsXG4gICAgICAgICAgMjI2LFxuICAgICAgICAgIDExMSxcbiAgICAgICAgICA2OSxcbiAgICAgICAgICAxNjQsXG4gICAgICAgICAgNTIsXG4gICAgICAgICAgMjE5LFxuICAgICAgICAgIDEzMyxcbiAgICAgICAgICAxNjcsXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDEyNixcbiAgICAgICAgICA3MixcbiAgICAgICAgICA3N1xuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA5MCxcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgMzQsXG4gICAgICAgICAgNzksXG4gICAgICAgICAgMzQsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICAxOTcsXG4gICAgICAgICAgMTcxLFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDIxMSxcbiAgICAgICAgICAxNjgsXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDQsXG4gICAgICAgICAgNjYsXG4gICAgICAgICAgNixcbiAgICAgICAgICAxNTQsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgMTY2LFxuICAgICAgICAgIDE4MyxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAyNDYsXG4gICAgICAgICAgMjIzLFxuICAgICAgICAgIDQ1LFxuICAgICAgICAgIDIwMixcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDIxNyxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAxMTlcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMjcsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMTk5LFxuICAgICAgICA3OCxcbiAgICAgICAgODQsXG4gICAgICAgIDQ5LFxuICAgICAgICA3MixcbiAgICAgICAgMjE3LFxuICAgICAgICA4OCxcbiAgICAgICAgMTI5LFxuICAgICAgICAyMTIsXG4gICAgICAgIDcxLFxuICAgICAgICAxMjIsXG4gICAgICAgIDI1MCxcbiAgICAgICAgOTMsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMTQzLFxuICAgICAgICA0MyxcbiAgICAgICAgNzQsXG4gICAgICAgIDI2LFxuICAgICAgICA0OSxcbiAgICAgICAgODIsXG4gICAgICAgIDIzNSxcbiAgICAgICAgNzYsXG4gICAgICAgIDIzNixcbiAgICAgICAgOTksXG4gICAgICAgIDEyNSxcbiAgICAgICAgMTA5LFxuICAgICAgICAxNjYsXG4gICAgICAgIDQsXG4gICAgICAgIDc2LFxuICAgICAgICAxOTMsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMjExLFxuICAgICAgICAyMTgsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMTk0LFxuICAgICAgICAyMDgsXG4gICAgICAgIDExMSxcbiAgICAgICAgMjI3LFxuICAgICAgICAxNjcsXG4gICAgICAgIDc4LFxuICAgICAgICA0MyxcbiAgICAgICAgNDQsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTk0LFxuICAgICAgICA3MSxcbiAgICAgICAgNzYsXG4gICAgICAgIDUyLFxuICAgICAgICAxNzksXG4gICAgICAgIDEyOSxcbiAgICAgICAgMTIxLFxuICAgICAgICA2NyxcbiAgICAgICAgNzgsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTUwLFxuICAgICAgICA5MixcbiAgICAgICAgMTI5LFxuICAgICAgICA1MyxcbiAgICAgICAgMTQ3LFxuICAgICAgICAyNDIsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTAyLFxuICAgICAgICAxMzNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDEzMyxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJrQXVQcW52QnQ2bkoxQzR3VFFSZ2VxMjEzOFJrNStaVGU5Q25kMnY3bWtrPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkyMzAzODY1MjA2N0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiNEE2NkVFQjA5REVCNkI3MUNGQUVDRUVDOURFOTIwOTBcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzUyMDU3MTQ1XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTIzMDM4NjUyMDY3QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI4MDU4QkM5NDg3NEU5OTMzNjNDOURFMjA1QTExNDBCQlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3NTIwNTcxNDVcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwibGgyeFl1b2lSN09xT1RGc2dhMGw3QVwiLFxuICBcInBob25lSWRcIjogXCI2MDJjY2EwOS1kZjgxLTQwMWEtOWNjNy0yMDRkZGVlNzYxMGRcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjEsXG4gICAgICA3MyxcbiAgICAgIDI1NCxcbiAgICAgIDIwNSxcbiAgICAgIDcxLFxuICAgICAgMTEsXG4gICAgICAxNixcbiAgICAgIDY3LFxuICAgICAgMTYxLFxuICAgICAgMTcyLFxuICAgICAgMTA4LFxuICAgICAgMTk3LFxuICAgICAgMjM2LFxuICAgICAgMzUsXG4gICAgICAxNDQsXG4gICAgICAxNjMsXG4gICAgICA0NSxcbiAgICAgIDI0NSxcbiAgICAgIDI0NCxcbiAgICAgIDE2NFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IGZhbHNlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTUzLFxuICAgICAgNjEsXG4gICAgICAxNTUsXG4gICAgICA0OSxcbiAgICAgIDIyOSxcbiAgICAgIDE2LFxuICAgICAgMTQxLFxuICAgICAgNTYsXG4gICAgICAxNTUsXG4gICAgICAxMzMsXG4gICAgICAxMTEsXG4gICAgICAxNjksXG4gICAgICAxNTEsXG4gICAgICAyMjYsXG4gICAgICAyMDEsXG4gICAgICAxNDYsXG4gICAgICAxNjUsXG4gICAgICAyMTcsXG4gICAgICAyMjQsXG4gICAgICAyMjJcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNPWFhyc01FRUxPS3VjTUdHQVlnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcInljNlBnMXlVb2dhM2xtbVE3UGEweWNoV0dXSXpKS1ZSYzlleUhxbXh3aFE9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwidWNhKzhNRzF2Y3dnaXZ2ZkRZbyt1TUlIRGl6dUR5WmNQa09xZlZDV3l1alpiSlgvZ3FnVG9XVndFdFV0UDlhUGIyOHJQWFh0QlFRTjNJSUtaNjV2QVE9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiTXdBQmxYT3JkYncySXA5WE9lcVBYNHIxcXFGU2UrYUo5OW1TamErUzBORm1CNTBuVXNlYXlQdFQ4UnorWnlOSVZ5WUpvVUVoTkIwLzdoVE9sVUVWakE9PVwiXG4gIH0sXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCI5MjMwMzg2NTIwNjc6MjlAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjIxNTEzNTQ2NTU1ODExMDoyOUBsaWRcIixcbiAgICBcIm5hbWVcIjogXCJ8fCBNYXN0RXIgRyDwn5iBIHx8XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5MjMwMzg2NTIwNjc6MjlAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDE0MyxcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgOTIsXG4gICAgICAgICAgMTQ4LFxuICAgICAgICAgIDE2MixcbiAgICAgICAgICA2LFxuICAgICAgICAgIDE4MyxcbiAgICAgICAgICAxNTAsXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDE0NCxcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgMjQ2LFxuICAgICAgICAgIDE4MCxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDI1LFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDM2LFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICA4MSxcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDE3OCxcbiAgICAgICAgICAzMCxcbiAgICAgICAgICAxNjksXG4gICAgICAgICAgMTc3LFxuICAgICAgICAgIDE5NCxcbiAgICAgICAgICAyMFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzUyMDU3MTQyLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBSzNGXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLMl9fLmpzb24iOiAie1wia2V5RGF0YVwiOlwiSnR6MmlQcExBM1lFNGM4TU9kczg4aDVBSnE1OTY2RkJaU2NqUlVia0NrUT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMjE1MDE1OTA5LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3NTE4MjQ4NDQ4OTBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLM0IuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJCZkkwWEJQSHc1VnZRWVZza0E3TElyWmJDYXVENEdxMGh3eENmTHZOZW5VPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEyMTUwMTU5MDksXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTc1MTk3MTk3OTc4MFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUszQy5qc29uIjogIntcImtleURhdGFcIjpcImlIRmM3em11T0tCc3JWeDBCZHkzNFZkTkVORG1iNFNhWklVTnNzSHpRazg9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTIxNTAxNTkwOSxcImN1cnJlbnRJbmRleFwiOjIsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzUyMDU2NTU1MzY0XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSzNELmpzb24iOiAie1wia2V5RGF0YVwiOlwiOGwwaUhSdUxoSXpwcmpEN3NhUTE5L1pRSVhUbUtsTWpCN2x3SHBBZ0hjZz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMjE1MDE1OTA5LFwiY3VycmVudEluZGV4XCI6MyxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3NTIwNTY2NjA0MjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLM0UuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJOU01vZnNQNjBuYUxWWTJYV3BWWFFnZHNMbERVMSsvUW9lZ0dsTEVvUTVnPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEyMTUwMTU5MDksXCJjdXJyZW50SW5kZXhcIjo1LFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsNV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSzNGLmpzb24iOiAie1wia2V5RGF0YVwiOlwiNDd3R1Awckx5NTNCRlVNcmpQQnlIOTMzcnNKcFRmVWVUcVBvcTlFNjNQTT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMjE1MDE1OTA5LFwiY3VycmVudEluZGV4XCI6NSxcImRldmljZUluZGV4ZXNcIjpbMCwxLDVdfSxcInRpbWVzdGFtcFwiOlwiMTc1MjA1NzEyMjczMlwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUszRy5qc29uIjogIntcImtleURhdGFcIjpcIlZBT1NET2pIczYybWFuZ203QW1STTZmNjlpU0VIcGRIdkdVVVl5SWZ0eUk9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTIxNTAxNTkwOSxcImN1cnJlbnRJbmRleFwiOjUsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzUyMDU3MTIzNzU1XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFCa0FBSzNBLmpzb24iOiAie1wia2V5RGF0YVwiOlwidTRyc2xiWUhkZHZjRkFMZDh5bVdXT1ZjWXRObnljWHF6UnFjbDNseDROaz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMjE1MDE1OTA5LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwyNV19LFwidGltZXN0YW1wXCI6XCIxNzUxODI0ODUwNjAxXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFCa0FBSzNDLmpzb24iOiAie1wia2V5RGF0YVwiOlwiSmtlbzhrWEJTNGhGSytJUXZCUG1xUkFRUitJU0lsU1VDL0hsUWVhaXBLRT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMjE1MDE1OTA5LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwyNV19LFwidGltZXN0YW1wXCI6XCIxNzUxOTc1NjkxOTg3XCJ9Igp9"  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.0.1-developement-x",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ GlobalTechInfo ® 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@GlobalTechInfo"),
 
  author : process.env.PACK_AUTHER|| "Raju Boss",
  packname: process.env.PACK_NAME || "Raju Boss",
  botname : process.env.BOT_NAME  || "Suhail-XMD",
  ownername:process.env.OWNER_NAME|| "Raju Boss",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "yepeTQaFk7r9ymusihgXYvdN",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "sk_e17fe171b8d395b9df440e504aa8aeaacb08ead66db9692e";
global.aitts_Voice_Id = process.env.AITTS_ID|| "wHI7GVgoHNG9c8H7zXAt";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
